### ISSUE TITLE
TODO: Quick Start

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/workers-docs#24]
- [x] Move Cloudflare API keys/configuration section into re-usable part in Reference
- [x] Link to reference section of docs
- [x] Update generate project screenshot when JS support lands in wrangler
- [x] Update “Preview your Worker” image when JS support lands in Wrangler
- [x] Update “Publish your Project” section with Zoneless + Wrangler setup
- [x] Update “Install Wrangler” link
