### ISSUE TITLE
TODO: Guides, Build an Application: "Tutorial"

### ISSUE THREAD

**Issue by kristianfreeman** [cloudflare/workers-docs#25]
- [ ] Move Cloudflare API keys/configuration section into re-usable part in Reference
- [ ] Link to final version of codebase on GitHub
- [ ] Explain that users need to know the script-name.subdomain.workers.dev URL they’re deploying to, before creating Slack config
- [ ] Router NPM package?
- [ ] Wrangler screenshot for build/publish
- [ ] Link to GitHub source for Slack bot code
- [ ] Link to second tutorial (“Building and deploying a serverless function on Cloudflare Workers”)
- [ ] Link to Template Gallery
